OB-0018
obama-imd/obama pull request #113
Opened 2024-10-28 18:09 UTC by RamonJales

**Por favor, informe se a PR segue os requisitos obrigatórios:**

- [x] Arquivos alterados/adicionados seguem o padrão _Camel Case_;
- [x] Integração com swagger funcionando;
- [x] Testes das camadas repository, service e controller.
- [x] Verificao a necessidade de cache e se sim, implementado?
- [x] A última linha de todos os arquivos estão com uma linha em branco?

**Motivação para a criação da PR**
Motivação: #47

**O que foi feito**
    - endpoint de salvar o plano de aula
    - seus testes
    - foi feito um método `any` personalizado para o teste do adapter, pois ao usar o eny padrão do `Mockito` ele estava retornando `null`.

**Screenshots**
![image](https://github.com/user-attachments/assets/e60c6f4f-320d-4a7c-8275-87dee76dee2f)

2024-10-28 23:12 UTC, vitorhenriquec commented on src/main/resources/db/migration/V15__inserir_campo_avaliacao_plano_aula.sql
Atualiza a sua branch em relação a main e atualiza o nome do arquivo para V16.

2024-10-28 23:16 UTC, vitorhenriquec requested changes
Coloquei uns comentários simples

2024-10-28 23:16 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/handler/AnoEnsinoExceptionHandler.kt
> +}
Adiciona linha em branco no fim do arquivo.

2024-10-28 23:16 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/handler/DisciplinaExceptionHandler.kt
> +}
Adiciona linha em branco no fim do arquivo.

2024-10-28 23:16 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/handler/NivelEnsinoExceptionHandler.kt
> +}
Adiciona linha em branco no fim do arquivo.

2024-10-29 20:38 UTC, RamonJales commented on src/main/resources/db/migration/V15__inserir_campo_avaliacao_plano_aula.sql
Tudo certo!

2024-10-29 20:43 UTC, vitorhenriquec approved these changes

2024-10-30 23:13 UTC, merged