Feature/OB-007 (Buscar por Id)
obama-imd/obama pull request #38
Opened 2024-04-13 15:00 UTC by Kywal

**Por favor, informe se a PR segue os requisitos obrigatórios:**

- [x] Arquivos alterados/adicionados seguem o padrão _Camel Case_;
- [x] Integração com swagger funcionando;
- [ ] Testes das camadas repository, service e controller.
- [x] Verificação da necessidade de cache e se sim, implementado?
- [ ] A última linha de todos os arquivos estão com uma linha em branco?

**Motivação para a criação da PR**
Issue #18 

**O que foi feito**
O endpoint de busca por Id com rota `{id}`. 
Obs: Fiz a PR para discutir/validar algumas alterações no projeto antes de dar continuidade.

**Screenshots**
--TODO

**O que faltou desenvolver**
Os testes, mas estou trabalhando neles

2024-04-13 15:27 UTC, Kywal commented
**Questões para debate:**

- Cache: Como o endpoint lida apenas com 1 objeto por vez não vi necessidade para implementar cache;

- Mudança no model de OA: Modifiquei o model para conseguir retornar informações relacionadas a entidade ObjetoAprendizagemPlataforma e gostaria de saber se tá tudo bem com isso;

- Alteração nos nomes dos gateway: Quero alterar o nome do OAGateway atual para CurriculoOAGateway ou algo similar, para deixar o OAGateway como interface central dos métodos mais comuns relacionados a OA, como o procurarPorId. 

@vitorhenriquec Assim que possível por favor manda um retorno sobre essas questões. Gratidão 🤝

2024-04-21 16:58 UTC, vitorhenriquec requested changes
Alguns pontos:
- Porque o workflow da cobertura não rodou na sua PR? Sua branch está atualizada em relação a main?
- Além do resource é interessante que se crie teste para o gateway e usecase criado. Lembre-se você adicionou novo código logo ele precisa ser testado em todas as classes que houve acréscimo ou alteração.
- Para resolver o problema de você esquecer a linha em branco no fim do arquivo, tem este link: https://stackoverflow.com/questions/16761227/how-to-make-intellij-idea-insert-a-new-line-at-every-end-of-file

2024-04-21 16:58 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/oa/domain/usecase/ObjetoAprendizagemUseCaseImpl.kt
> +        logger.info("method={};", "buscarPorId")
Chama direito o gateway IdObjetoAprendizagemGateway não precisa do beanFactory. Lembre-se que o Bean Factory foi utilizado antes porque havia dois possíveis caminhos BNCC e PCN.

2024-04-21 16:58 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/mapper/ObjetoAprendizagemPlataformaEntityMapper.kt
> +}
Adiciona linha em branco no fim do arquivo.

2024-04-21 16:58 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/adapter/ObjetoAprendizagemDatabaseGatewayAdapter.kt
> +            .findById(id, pageable).map { it.toModel() }
Porque você paginou a busca por um objeto? Utiliza-se paginação para um retorno de vários objetos. Você considerou o cenário: O que acontece se não achar um objeto por aquele id?

2024-04-21 16:58 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/resource/ObjetoAprendizagemResource.kt
> +        ApiResponse(
O que acontece caso não encontre um OA, qual tipo de ApiResponse é respondido ao usuário que interage com a API?

2024-04-21 16:58 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/resource/ObjetoAprendizagemResourceImpl.kt
> +        pageable: Pageable): Page<BuscarOaIdResponse> {
Não utilizamos paginação para um retorno de apenas um objeto, apenas para quando retorna vários.

2024-04-21 16:58 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/resource/exchange/BuscarOaIdResponse.kt
> +)
Adicionar linha no fim do arquivo.

2024-04-21 16:58 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/resource/exchange/BuscarOaIdResponse.kt
> +    val dataLancamento: LocalDate?,
Lembre-se que é interessante que na chamada o retorno seja snake_case e não camelCase.

2024-04-21 16:58 UTC, vitorhenriquec commented on src/test/kotlin/br/ufrn/imd/obama/oa/infrastructure/resource/ObjetoAprendizagemResourceImplTest.kt
> +    fun `Deve retornar objeto de aprendizado buscado pelo id`() {
E o contrário? E se o id não existir na nossa base?

2024-04-24 16:30 UTC, Kywal commented on src/main/kotlin/br/ufrn/imd/obama/oa/domain/model/ObjetoAprendizagem.kt
> +	val plataformas: List<ObjetoAprendizagemPlataforma>,
Para que se consiga retornar os atributos `Lista de Acessos (link, tipo, plataforma de acesso)` citados na #18. Da forma que estava antes só recebíamos o id e o nome da plataforma.

Acredito que daria para resolver buscando a plataforma pelo Id, mas além de ainda ter que implementar essa busca, me pareceu bom substituir por um objeto mais abrangente/completo.

2024-05-18 11:37 UTC, vitorhenriquec requested changes

2024-05-18 11:37 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/adapter/ObjetoAprendizagemDatabaseGatewayAdapter.kt
> +        logger.info("method={};", "procurarPorId")
Faltou logar o id aqui.

2024-05-18 11:37 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/resource/ObjetoAprendizagemResourceImpl.kt
> +import org.springframework.web.bind.annotation.*
É interessante que os imports seja especificos e não génericos assim

2024-05-18 11:37 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/adapter/ObjetoAprendizagemDatabaseGatewayAdapter.kt
> +                    .orElseThrow()
Ele lança que exceção aqui? 

Ela é tratado no momento que chega no controlado? Como o que? Caso não saiba do que eu tou falando tem este artigo https://www.baeldung.com/kotlin/spring-rest-error-handling

2024-05-18 11:37 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/resource/ObjetoAprendizagemResourceImpl.kt
> +            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(null)
Não se trata as exceções assim no spring. Existe um recurso chamado ControllerAdvice. Você pode achar mais sobre ele aqui https://www.baeldung.com/kotlin/spring-rest-error-handling

2024-05-18 14:38 UTC, vitorhenriquec commented
Sugiro que atualize a sua branch em relação a main.

2024-05-21 19:57 UTC, vitorhenriquec requested changes

2024-05-21 20:12 UTC, Kywal commented on src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/repository/ObjetoAprendizagemRepository.kt
> +    fun buscarPorId(@Param("id") id: Long): ObjetoAprendizagemEntity?
Eu tentei usar o findById mas ele retorna Optional por padrão, aí optei por criar esse personalizado. 

Qual seria a alternativa que você indicaria?

2024-05-21 20:28 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/repository/ObjetoAprendizagemRepository.kt
> +    fun buscarPorId(@Param("id") id: Long): ObjetoAprendizagemEntity?
Seria usar esse mesmo. Era só saber trata-lo.

2024-05-21 20:28 UTC, vitorhenriquec approved these changes

2024-05-21 22:10 UTC, merged