Feature/ob 0008
obama-imd/obama pull request #39
Opened 2024-04-17 01:30 UTC by RamonJales

**Por favor, informe se a PR segue os requisitos obrigatórios:**

- [x] Arquivos alterados/adicionados seguem o padrão _Camel Case_;
- [ ] Integração com swagger funcionando;
- [x] Testes das camadas repository, service e controller.
- [x] Verificao a necessidade de cache e se sim, implementado?
- [x] A última linha de todos os arquivos estão com uma linha em branco?

**Motivação para a criação da PR**
Issue #21.

**O que foi feito**
- Criação do método **busca paginada por habilidades que considere o id do ano de ensino e o id do tema curricular** no repository, service e controller da entidade Habilidade. E seus respectivos testes.
- Utilzando paginação, busca mesmo não tendo passado os valores e cache

**Screenshots**

**O que faltou desenvolver**
Não consegui verificar o swager, estou com erro de firewall quando acesso a URL.

2024-04-17 01:31 UTC, RamonJales commented
Curiosidade, qual o motivo de: "**A última linha de todos os arquivos estão com uma linha em branco**"?

2024-04-18 12:02 UTC, RamonJales commented
Na classe `habilidadeResponse`, foi usado `PropertyNamingStrategies.SnakeCaseStrategy` ao invés  `PropertyNamingStrategy.SnakeCaseStrategy` pois esse estava depreciado.

2024-04-21 17:06 UTC, vitorhenriquec requested changes

2024-04-21 17:06 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/resource/HabilidadeResource.kt
> +    @Operation(summary = "Endpoint para listar de forma páginada habilidades buscadas pelo Id da habilidade e do tema curricular")
Sugestão: "Endpoint para listar de forma páginada habilidades filtradas pelo Id da habilidade e do tema curricular"

2024-04-21 17:06 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/resource/HabilidadeResourceImpl.kt
> +    @Cacheable(cacheNames = ["Habilidades"])
Como já está paginada não vejo a necessidade do cache.

2024-04-21 17:06 UTC, vitorhenriquec commented on src/test/kotlin/br/ufrn/imd/obama/oa/domain/usecase/HabilidadeUsecaseImplTest.kt
Legal os cenários de teste

2024-04-21 17:06 UTC, vitorhenriquec commented on src/test/kotlin/br/ufrn/imd/obama/oa/infrastructure/resource/HabilidadeResourceImplTest.kt
> +    fun `Deve retornar ok quando lista descritores passando os dois parametros corretos`() {
Não é lista as habilidades?

2024-04-21 17:06 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/resource/exchange/HabilidadeResponse.kt
> +    @JsonProperty("nome-ano-ensino")
A ideia é usar o padrão **snake_case**. Dê uma procurar como esse padrão funciona.

2024-04-23 19:51 UTC, vitorhenriquec commented
> Curiosidade, qual o motivo de: "**A última linha de todos os arquivos estão com uma linha em branco**"?

Mas porque fica "reclamando" no momento do code review do github

2024-04-23 19:52 UTC, vitorhenriquec commented
> Na classe `habilidadeResponse`, foi usado `PropertyNamingStrategies.SnakeCaseStrategy` ao invés `PropertyNamingStrategy.SnakeCaseStrategy` pois esse estava depreciado.

Sim, numa outra tarefa vai ser interessante fazer essa mudança paras as outras responses.

2024-04-23 20:10 UTC, vitorhenriquec approved these changes

2024-04-24 01:00 UTC, merged