Feature/ob 0016
obama-imd/obama pull request #44
Opened 2024-04-27 01:58 UTC by RamonJales

**Por favor, informe se a PR segue os requisitos obrigatórios:**

- [x] Arquivos alterados/adicionados seguem o padrão _Camel Case_;
- [x] Integração com swagger funcionando;
- [x] Testes das camadas repository, service e controller.
- [x] Verificao a necessidade de cache e se sim, implementado?
- [x] A última linha de todos os arquivos estão com uma linha em branco?

**Motivação para a criação da PR**
Criação da entidade usuário.

**O que foi feito**
- criado o domain/model usuário
- criado infrastructure/entity usuário
- criado o script para criação da tabela

2024-04-27 01:59 UTC, RamonJales commented
O UsuarioEntity está dando um erro estranho, fica vermelho, não sei se é a minha IDE. Alguém pode da pull ai na sua máquina pra poder verificar?

2024-04-27 02:00 UTC, RamonJales commented
Devo criar apenas o script para a criação de tabela ou devo acrescentar um para inserção de alguns dados?

2024-04-27 02:00 UTC, RamonJales commented
O atributo Enum deve ser colocado como string?

2024-05-03 14:07 UTC, vitorhenriquec requested changes

2024-05-03 14:07 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/oa/domain/enums/Role.kt
> +}
Adiciona linha em branco no fim do arquivo

2024-05-03 14:07 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/oa/domain/enums/TipoCadastro.kt
> +}
Adiciona linha em branco no fim do arquivo

2024-05-03 14:07 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/entity/UsuarioEntity.java
> +        val tipoCadastro:TipoCadastro,
\Não precisa disto @Enumerated(EnumType.STRING) ?

2024-05-03 14:07 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/entity/UsuarioEntity.java
> +        @column(name = "nome")
Cadê no @Column a indicação de obrigatoriedade?

2024-05-07 12:57 UTC, RamonJales commented on src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/entity/UsuarioEntity.java
> +        val tipoCadastro:TipoCadastro,
precisa sim! Esqueci.

2024-05-07 13:06 UTC, RamonJales commented on src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/entity/UsuarioEntity.java
> +        @column(name = "nome")
No @Column? Eu usei o @NotNull para isso.

2024-05-07 13:07 UTC, RamonJales commented
Devemos ter o campo senha como atributo? Não deveria ter apenas no token?

2024-05-07 14:08 UTC, vitorhenriquec approved these changes

2024-05-07 14:14 UTC, merged