Feature/OB-0012: Cadastrar novo usuario (VERSÃO NOVA)
obama-imd/obama pull request #62
Opened 2024-05-25 18:10 UTC by RamonJales

**Por favor, informe se a PR segue os requisitos obrigatórios:**

- [x] Arquivos alterados/adicionados seguem o padrão _Camel Case_;
- [x] Integração com swagger funcionando;
- [ ] Testes das camadas repository, service e controller.
- [x] Verificao a necessidade de cache e se sim, implementado?
- [x] A última linha de todos os arquivos estão com uma linha em branco?

OBS: aconteceu uns problemas com minha pr antiga. Tive que fazer outra.

**Motivação para a criação da PR**
Veja: #31 

**O que foi feito**
Foi feito o endpoint para salvar usuario com a senha encryptada. E uma configuração inicial do springsecurity que no momento está permitindo todas as rotas.

**Screenshots**
![Captura de tela de 2024-05-22 19-42-12](https://github.com/obama-imd/obama/assets/85131757/b70c8f58-9d44-4d7f-a5aa-f4eae6333953)

**O que faltou desenvolver**
Testes mais robustos.

2024-05-25 18:53 UTC, vitorhenriquec requested changes
É importante a existência de testes nos controladores. No minimo testar os cenários:

- Sucesso na criação
- 400 quando já existe um usuário cadastrado com aquele e-mail

2024-05-25 18:53 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/usuario/infrastructure/resource/UsuarioDatabaseResource.kt
> +}
Adiciona linha em branco no fim do arquivo.

2024-05-25 18:53 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/usuario/infrastructure/mapper/UsuarioMapper.kt
> +}
Adiciona linha em branco no fim do arquivo.

2024-05-25 18:53 UTC, vitorhenriquec commented on src/test/kotlin/br/ufrn/imd/obama/usuario/domain/usecase/UsuarioDatabaseUseCaseImplTest.kt
> +}
Adiciona linha em branco no fim do arquivo.

2024-05-25 18:53 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/usuario/domain/usecase/UsuarioDatabaseUseCaseImpl.kt
> +}
Adiciona linha em branco no fim do arquivo.

2024-05-25 18:53 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/usuario/domain/usecase/UsuarioDatabaseUseCase.kt
> +interface UsuarioDatabaseUseCase {
Não seria melhor alterar para UsuarioUseCase.

2024-05-25 18:53 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/usuario/infrastructure/resource/exchange/UsuarioResponse.kt
> +)
1. Adiciona linha em branco no fim do arquivo.
2. Você expôs aqui alguns dados que não sei nem se faz sentido ter no corpo da resposta. Por questões de segurança, esse response deve conter apenas nome, sobrenome e email.
3. Apesar de eu não ter descrito na tarefa trocar a resposta para um 201 (é melhor).

2024-05-25 18:53 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/usuario/infrastructure/resource/UsuarioDatabaseResourceImpl.kt
> +            tipoCadastro = usuario.tipoCadastro,
Essa parte de montar o usuário indicando o tipo do papel seria interessante estar no useCase.

2024-05-25 18:53 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/usuario/infrastructure/resource/UsuarioDatabaseResourceImpl.kt
> +        @RequestBody usuario: Usuario
1. Aqui seria interesante uma classe do tipo request que só exige nome, sobrenome, email e senha não espera-se por ativo e tipo de cadastro(eu não mencionei mas o tipo de cadastro nessa fluxo por enquanto será somento o padrão). 
2. Encriptar a senha deveria fazer parte do UsuarioUseCase.

2024-05-25 18:53 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/usuario/domain/usecase/UsuarioDatabaseUseCaseImpl.kt
> +    override fun salvarUsuario(usuario: Usuario): Usuario {
1. Acho que seria bom alterar o nome talvez para cadastrarUsuario
2. É importante ter uma validação extra antes de chamar o gateway afinal o e-mail é um dado único na tabela usuário. A aplicação deve lançar uma exceção para caso o e-mail que vem do controlador já exista salvo na nossa base. A aplicação deve interpretar no fim das contas essa exceção lançada como 400.

É no exception controller que é possível converter exceções lançadas em respostas personalizadas.

2024-05-25 18:53 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/usuario/domain/usecase/UsuarioDatabaseUseCaseImpl.kt
> +class UsuarioDatabaseUseCaseImpl(
Não seria melhor alterar o nome para UsuarioUseCaseImpl?

2024-05-25 18:53 UTC, vitorhenriquec commented on src/test/kotlin/br/ufrn/imd/obama/usuario/domain/usecase/UsuarioDatabaseUseCaseImplTest.kt
É importante adicionar um teste sobre o ponto que eu comentei da validação de e-mail.

2024-05-25 18:53 UTC, vitorhenriquec commented on src/test/kotlin/br/ufrn/imd/obama/usuario/util/UsuarioDatabaseUtil.kt
> +}
Adiciona linha em branco no fim do arquivo.

2024-05-25 21:11 UTC, vitorhenriquec commented
Atualize em relação a main e não esqueça de colocar o filtro que permite a rota de cadastro ser acessado sem precisar estar autenticado.

2024-05-30 17:25 UTC, RamonJales commented on src/main/kotlin/br/ufrn/imd/obama/usuario/infrastructure/resource/UsuarioDatabaseResourceImpl.kt
> +            tipoCadastro = usuario.tipoCadastro,
Eu teria que passar o ` CadastrarUsuarioRequest` para um `usuario` com um `mapper`, pois é oq meu `useCase` recebe. E, no Use case montar o objeto para ser salvo no banco de dados. Ou eu poderia fazer meu `useCase` receber um ` CadastrarUsuarioRequest`, mas acho que isso iria ferir a arquitetura limpa. Qual caminho devo seguir?

2024-05-30 22:26 UTC, RamonJales reviewed
- No `UsuarioDatabaseResourceImplTest` não estamos mais mocando o UseCaseImpl?
- Transferi a montagem do usuario no salvar do `controller`, agora esta fazendo isso a partir de uma função no `UseCase`, essa é uma forma válida?
- A validação do `@Email`, não está funcionando. Tentei mudar a notação de lugar mas da no mesmo. Ou seja, ainda consigo salvar o usuário com o email inválido.

2024-05-30 23:58 UTC, vitorhenriquec commented
> * No `UsuarioDatabaseResourceImplTest` não estamos mais mocando o UseCaseImpl?
> * Transferi a montagem do usuario no salvar do `controller`, agora esta fazendo isso a partir de uma função no `UseCase`, essa é uma forma válida?
> * A validação do `@Email`, não está funcionando. Tentei mudar a notação de lugar mas da no mesmo. Ou seja, ainda consigo salvar o usuário com o email inválido.

1. No UsuarioDatabaseResourceImplTest não estamos mais mocando o UseCaseImpl? 
2. ransferi a montagem do usuario no salvar do controller, agora esta fazendo isso a partir de uma função no UseCase, essa é uma forma válida? **R: Não faz muito sentido, seria melhor do jeito que tava ou você poderia criar um método especfico que converte a classe CadastrarUsuarioRequest para a classe Usuario (parecido com a ideia do mapper).**
3. A validação do @Email, não está funcionando. Tentei mudar a notação de lugar mas da no mesmo. Ou seja, ainda consigo salvar o usuário com o email inválido. **R: Falta a anotação valid na linha 40 da classe UsuarioDatabaseResourceImpl.
4. É melhor trocar o nome UsuarioDatabaseResourceImpl e UsuarioDatabaseResource respectivamente para UsuarioResourceImpl e UsuarioResource.
5. Não é legal tratar a conversão das exceções UsuarioExistenteException e a Exception para ResponseEntity da meneira que você tratou no UsuarioDatabaseResourceImpl. Olha o ObjetoAprendizagemExceptionHandler. Só precisa definir um classe parecida com ela mas para o contexto de pacotes de usuário.

2024-05-31 02:40 UTC, RamonJales commented
> 2. R: Não faz muito sentido, seria melhor do jeito que tava ou você poderia criar um método especfico que converte a classe CadastrarUsuarioRequest para a classe Usuario (parecido com a ideia do mapper).
> 3. A validação do @Email, não está funcionando. Tentei mudar a notação de lugar mas da no mesmo. Ou seja, ainda consigo salvar o usuário com o email inválido. **R: Falta a anotação valid na linha 40 da classe UsuarioDatabaseResourceImpl.


3. Desfiz as mudanças. No momento existe uma verificação manual para validar a senha. Posteriormente se conseguir concertar o problema `3` eu retiro.
   3.1.  Mas não entendi o pedido [aqui](https://github.com/obama-imd/obama/pull/62#discussion_r1614803297). Se eu tenho que delegar a ação de montagem para o `UseCase`, eu tenho que fazer uma conversão do `request` para o `Usuario` e então mandar para o `UseCase` e teria que setar o `papel = Papel.PADRAO` na minha classe `resource` de todo jeito. Seria muito bom se eu pudesse simplesmente setar como nulo, mas não posso.
4. Não da certo. Aparentemente por conta que o método implementa outro. A anotação valid deve ficar na interface. Mas mesmo assim não funciona. Veja [esta discussão](https://github.com/UniKnow/AgileDev/issues/3#issuecomment-98736340).

2024-05-31 13:04 UTC, vitorhenriquec commented
> > 2. R: Não faz muito sentido, seria melhor do jeito que tava ou você poderia criar um método especfico que converte a classe CadastrarUsuarioRequest para a classe Usuario (parecido com a ideia do mapper).
> 
> > 3. A validação do @Email, não está funcionando. Tentei mudar a notação de lugar mas da no mesmo. Ou seja, ainda consigo salvar o usuário com o email inválido. **R: Falta a anotação valid na linha 40 da classe UsuarioDatabaseResourceImpl.
> 
> 
> 
> 
> 
> 2. Desfiz as mudanças. No momento existe uma verificação manual para validar a senha. Posteriormente se conseguir concertar o problema `3` eu retiro.
> 
>    2.1.  Mas não entendi o pedido [aqui](https://github.com/obama-imd/obama/pull/62#discussion_r1614803297). Se eu tenho que delegar a ação de montagem para o `UseCase`, eu tenho que fazer uma conversão do `request` para o `Usuario` e então mandar para o `UseCase` e teria que setar o `papel = Papel.PADRAO` na minha classe `resource` de todo jeito. Seria muito bom se eu pudesse simplesmente setar como nulo, mas não posso.
> 
> 3. Não da certo. Aparentemente por conta que o método é uma implementação(veja [esta discussão](https://github.com/UniKnow/AgileDev/issues/3#issuecomment-98736340).). A anotação `@Valid` deve ficar na interface. Mas mesmo assim não funciona.
> 
> 
> 
> 

2. Não entendi, conversamos melhor na reunião.
3. Na request CadastrarUsuarioRequest para funcionar a validação falta ficar tipo @field:NotBlank.
![image](https://github.com/obama-imd/obama/assets/17128609/e801b7ce-7826-4ca4-a951-b167ae98256f)

2024-06-04 23:01 UTC, vitorhenriquec approved these changes

2024-06-07 00:05 UTC, merged