Feature/ob 0013
obama-imd/obama pull request #72
Opened 2024-06-11 23:10 UTC by RamonJales

**Por favor, informe se a PR segue os requisitos obrigatórios:**

- [x] Arquivos alterados/adicionados seguem o padrão _Camel Case_;
- [x] Integração com swagger funcionando;
- [x] Testes das camadas repository, service e controller.
- [x] Verificao a necessidade de cache e se sim, implementado?
- [x] A última linha de todos os arquivos estão com uma linha em branco?

**Motivação para a criação da PR**

Issue: #32.

**O que foi feito**
Endpoint para ativar o usuario por token. Passamos o token no body da requisição. E criado o buscarPorToken.

2024-06-14 20:10 UTC, vitorhenriquec requested changes

2024-06-14 20:10 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/usuario/domain/usecase/UsuarioUseCaseImpl.kt
> +        return Optional.ofNullable(usuarioGateway.buscarPorToken(token))
Você pode usar no método do repositório o Optional<Usuario> não precisa fazer desse jeito.

2024-06-14 20:10 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/usuario/infrastructure/repository/UsuarioRepository.kt
> +    fun findByToken(token: String): UsuarioEntity?
Aqui se quiser pode usar Optional<UsuarioEntity>

2024-06-14 20:10 UTC, vitorhenriquec commented on src/test/kotlin/br/ufrn/imd/obama/usuario/infrastructure/resource/UsuarioResourceImplTest.kt
> +    val tokenTeste = "teste"
Acho que seria interessante que fosse parecido com o token, tipo UUID.

2024-06-14 20:10 UTC, vitorhenriquec commented on src/test/kotlin/br/ufrn/imd/obama/usuario/infrastructure/resource/UsuarioResourceImplTest.kt
> +            tokenTeste
Na definição da tabela usuário o token não é único?

2024-06-14 20:11 UTC, vitorhenriquec commented
Você chegou a testar se o fluxo: cadastrar novo usuário, ativar e fazer login?

2024-06-15 17:11 UTC, RamonJales commented on src/main/kotlin/br/ufrn/imd/obama/usuario/infrastructure/resource/UsuarioResourceImpl.kt
> +        if(obj.isPresent && obj.get().ativo){
Ok! Eu fui pelo o que tinha na issue: `(...) e caso o usuário já esteja ativo retorne um código 200 informando que a conta está ativa.`

2024-06-15 19:22 UTC, RamonJales commented
> Você chegou a testar se o fluxo: cadastrar novo usuário, ativar e fazer login?
Bom, ao fazer os testes separadamente já deveria servir como o fluxo não? Mas de toda forma fiz acabei fazendo

2024-06-15 19:30 UTC, RamonJales commented on src/test/kotlin/br/ufrn/imd/obama/usuario/infrastructure/resource/UsuarioResourceImplTest.kt
> +            tokenTeste
Ele não foi marcado como único. Tanto é que os testes estão passando, devo criar uma migration para a atualização, correto?

2024-06-18 01:09 UTC, RamonJales commented on src/main/kotlin/br/ufrn/imd/obama/usuario/infrastructure/adapter/UsuarioDatabaseGatewayAdapter.kt
> +        return usuarioRepository.findByToken(token)?.toModel() ?: throw UsuarioNaoEncontradoException("Usuário Não encontrado")
![Captura de tela de 2024-06-17 21-37-55](https://github.com/obama-imd/obama/assets/85131757/2b4a9eb5-53f6-46d5-a2aa-cef70ab21c0f)
indice criado

2024-06-18 23:00 UTC, vitorhenriquec approved these changes

2024-06-21 06:31 UTC, Kywal requested changes
<img width="883" alt="image" src="https://github.com/obama-imd/obama/assets/69535401/4e57e397-90da-4f4e-826f-6d2c724198d9">

De acordo com a descrição da issue [#32] é necessário retornar 204 no content quando não existir usuário com o token informado, mas ta retornando 400 bad request.

2024-06-21 06:31 UTC, Kywal commented on src/main/kotlin/br/ufrn/imd/obama/usuario/infrastructure/resource/UsuarioResourceImpl.kt
> +    override fun ativarUsuarioPorToken(@RequestBody ativarUsuarioRequest: AtivarUsuarioRequest): ResponseEntity<Void> {
o tipo de retorno deveria ser `ResponseEntity<Unit>`, não?

2024-06-22 15:07 UTC, Kywal commented
> De acordo com a descrição da issue [#32] é necessário retornar 204 no content quando não existir usuário com o token informado, mas ta retornando 400 bad request.

Nesse caso, @vitorhenriquec, qual o motivo de retornar 204 No Content e não 400 bad request?

2024-06-22 16:59 UTC, RamonJales commented
> De acordo com a descrição da issue [#32] é necessário retornar 204 no content quando não existir usuário com o token informado, mas ta retornando 400 bad request.

Vê os comentários anteriores, irá entender.

2024-06-22 18:02 UTC, Kywal commented
Entendi, não devemos informar se o token existe ou não para criar vulnerabilidades. Nesse caso @RamonJales, vou deixar o `requesting changes` de pé. Se lembra de excluir o caso de teste que verifica isso do 400 Bad Request.

2024-06-25 22:59 UTC, vitorhenriquec commented
Atualize sua branch em relação a main antes de mergear

2024-06-28 15:28 UTC, merged