Feature/OB-0021: Listagem de planos de aula
obama-imd/obama pull request #80
Opened 2024-07-01 17:08 UTC by RamonJales

**Por favor, informe se a PR segue os requisitos obrigatórios:**

- [x] Arquivos alterados/adicionados seguem o padrão _Camel Case_;
- [x] Integração com swagger funcionando;
- [x] Testes das camadas repository, service e controller.
- [x] Verificão a necessidade de cache e se sim, implementado?
- [x] A última linha de todos os arquivos estão com uma linha em branco?

**Motivação para a criação da PR**

#50 

**O que foi feito**
O endpoint para listar os planos de Aula e os testes do: resource; gatewayAdapter e Usecase.

2024-07-01 17:14 UTC, RamonJales commented
Ué, como o [PlanoAulaResourceImpl.kt](https://github.com/obama-imd/obama/blob/07f03175f9243a2b447142e410f7daa7b5d358dc/src%2Fmain%2Fkotlin%2Fbr%2Fufrn%2Fimd%2Fobama%2Fplanoaula%2Finfrastructure%2Fresource%2FPlanoAulaResourceImpl.kt) nçao foi testado 100%?

2024-07-02 23:03 UTC, vitorhenriquec requested changes

2024-07-02 23:03 UTC, vitorhenriquec commented on src/main/kotlin/br/ufrn/imd/obama/usuario/infrastructure/configuration/SecurityConfiguration.kt
> +                .requestMatchers(AntPathRequestMatcher.antMatcher(HttpMethod.GET ,"/v1/plano-aula")).authenticated()
Substitui aqui também, sem hifen

2024-07-05 12:30 UTC, vitorhenriquec requested changes
Detalhe que a tarefa pede os planos de aula do usuário, ou seja, os planos de aula no qual o usuário é autor. Onde isso é feito?

2024-07-05 12:51 UTC, Kywal commented
> Detalhe que a tarefa pede os planos de aula do usuário, ou seja, os planos de aula no qual o usuário é autor. Onde isso é feito?

Vitor, Ramon tá ocupado e me comunicou pra finalizar essa PR. Também não identifiquei, vou implementar.

2024-07-05 18:57 UTC, vitorhenriquec commented
> > Detalhe que a tarefa pede os planos de aula do usuário, ou seja, os planos de aula no qual o usuário é autor. Onde isso é feito?
> 
> Vitor, Ramon tá ocupado e me comunicou pra finalizar essa PR. Também não identifiquei, vou implementar.

Atualizei a sua branch em relação a main

2024-07-31 22:24 UTC, vitorhenriquec approved these changes
Você chegou a subir a aplicação e testar o cenário de passar o título e de não passar né?

2024-08-01 17:35 UTC, Kywal approved these changes

2024-08-02 14:38 UTC, RamonJales commented
> Você chegou a subir a aplicação e testar o cenário de passar o título e de não passar né?

Com titulo:
![image](https://github.com/user-attachments/assets/ca92dcc7-2265-4f27-b044-306fb480ade6)
Sem titulo:
![Captura de tela de 2024-08-02 11-36-37](https://github.com/user-attachments/assets/21930304-d097-4cde-97ba-c91b91237791)

2024-08-02 14:39 UTC, merged